@startuml

package "Azure" {
  [Flow Proxy]
}

package "Power Apps" {
  
  [Power Automate]
  
  database "Dataverse" {
    
  }
}

HTTP -right-> [Flow Proxy]
[Flow Proxy] -right-> [Power Automate]
[Power Automate] --> [Dataverse]

@enduml